FROM azul/zulu-openjdk-alpine:17-jre-headless
RUN mkdir -p app
WORKDIR /app
COPY /target/crowdfund-innovative-world-*.jar /app/crowdfund-innovative-world.jar
EXPOSE 8082
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","crowdfund-innovative-world.jar"]